codecov:
  notify:
    after_n_builds: 5 # keep in sync with .travis.yml number of builds

# datapagemap.c/.h are copied from Postgres, so let's remove it
# from report.  Otherwise, we would have to remove some currently
# unused methods to do not spoil the report.
ignore:
  - "**/datapagemap.*"
  - "**/*datapagemap*"
  - "datapagemap.*"
  - "datapagemap.c"
  - "datapagemap.h"
